// Generates downsized WebP copies of the homepage images and writes
// assets/image-thumbs.js (original path -> [thumb path, width, height]).
//
// The originals stay untouched: the Art lightbox still opens them at full
// resolution. Only the grid thumbnails, project cards and avatar use the
// small copies. Re-run after adding art to assets/art-data.js:
//
//   npm run thumbs
//
// Requires ImageMagick 7 (`magick`) on PATH. Existing thumbs newer than
// their source are skipped, so re-runs only process new or changed images.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const THUMB_DIR = '/assets/img/thumbs';

// Art grid columns render at most ~300px wide; 640px covers 2x displays.
const ART_WIDTH = 640;
// Featured project card / modal hero is ~700px wide.
const PROJECT_WIDTH = 1280;
const AVATAR_WIDTH = 256;

function loadArtPaths() {
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(path.join(ROOT, 'assets/art-data.js'), 'utf8'), sandbox);
  return sandbox.window.ART_CATEGORIES_RAW.flatMap((c) => c.images);
}

function projectPaths() {
  const src = fs.readFileSync(path.join(ROOT, 'assets/jsx/data/projects.js'), 'utf8');
  return [...new Set([...src.matchAll(/img: '([^']+)'/g)].map((m) => m[1]))];
}

function thumbPathFor(webPath) {
  const rel = webPath.replace(/^\/assets\/img\//, '');
  return `${THUMB_DIR}/${rel.replace(/\.[^.]+$/, '')}.webp`;
}

function makeThumb(webPath, width) {
  const src = path.join(ROOT, webPath);
  const thumbWeb = thumbPathFor(webPath);
  const out = path.join(ROOT, thumbWeb);
  const stale = !fs.existsSync(out) || fs.statSync(out).mtimeMs < fs.statSync(src).mtimeMs;
  if (stale) {
    fs.mkdirSync(path.dirname(out), { recursive: true });
    // -auto-orient bakes in the EXIF rotation (phone photos) before -strip
    // drops the metadata, so thumbs display the same way the originals do.
    // `>` only ever shrinks; small sources keep their size.
    execFileSync('magick', [src, '-auto-orient', '-strip', '-resize', `${width}x>`, '-quality', '80', out]);
  }
  const [w, h] = execFileSync('magick', ['identify', '-format', '%w %h', out]).toString().trim().split(' ').map(Number);
  return [thumbWeb, w, h];
}

const manifest = {};
for (const p of loadArtPaths()) manifest[p] = makeThumb(p, ART_WIDTH);
for (const p of projectPaths()) manifest[p] = makeThumb(p, PROJECT_WIDTH);
manifest['/assets/img/mepunk.png'] = makeThumb('/assets/img/mepunk.png', AVATAR_WIDTH);

const body = `// GENERATED by scripts/make-thumbs.mjs — do not edit by hand.
// Original image path -> [downsized WebP path, width, height].
window.IMAGE_THUMBS = ${JSON.stringify(manifest, null, 2)};
`;
fs.writeFileSync(path.join(ROOT, 'assets/image-thumbs.js'), body);
console.log(`${Object.keys(manifest).length} images -> ${THUMB_DIR}`);
